import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import QueryProvider from "./providers/QueryProvider";

const pretendard = localFont({
  src: "../public/fonts/pretendard/PretendardVariable.woff2",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className={`${pretendard.variable} antialiased`}>{children}</body>
      </QueryProvider>
    </html>
  );
}
