import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import QueryProvider from "./providers/QueryProvider";
import NavigationBar from "./components/NavigationBar";
import clsx from "clsx";
import { HeaderProvider } from "./components/header/HeaderContext";
import HeaderConsumer from "./components/header/HeaderConsumer";

const pretendard = localFont({
  src: "../public/fonts/pretendard/PretendardVariable.woff2",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <HeaderProvider>
          <body
            className={clsx(
              pretendard.variable,
              "mx-auto h-screen w-[375px] bg-background-tertiary antialiased shadow-md",
            )}
          >
            <HeaderConsumer />
            <main className="h-screen bg-background-primary">{children}</main>
            <NavigationBar />
          </body>
        </HeaderProvider>
      </QueryProvider>
    </html>
  );
}
