import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import QueryProvider from "./providers/QueryProvider";
import NavigationBar from "./components/NavigationBar";
import clsx from "clsx";
import { HeaderProvider } from "./components/header/HeaderContext";
import HeaderConsumer from "./components/header/HeaderConsumer";
import { AmplitudeProvider } from "./providers/AmplitudeProvider";
import { Suspense } from "react";
import ClientLayout from "./ClientLayout";

const pretendard = localFont({
  src: "../public/fonts/pretendard/PretendardVariable.woff2",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "빌리지",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AmplitudeProvider>
        <QueryProvider>
          <HeaderProvider>
            <body
              className={clsx(
                pretendard.variable,
                "mx-auto flex w-[375px] flex-col bg-background-tertiary antialiased shadow-md",
              )}
            >
              <ClientLayout>{children}</ClientLayout>
            </body>
          </HeaderProvider>
        </QueryProvider>
      </AmplitudeProvider>
    </html>
  );
}
